### ISSUE TITLE
Solid set?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-icons#1]
Is it possible to include solid icon set here?

![solid FTW](https://user-images.githubusercontent.com/35271042/54893212-f1696d00-4e71-11e9-8287-7400c0572144.gif)

**Comment by miguelsolorio** [comment]
These were part of the exploration we did early on so we probably won’t include this. This is just for our current icons.

**Comment by miguelsolorio** [comment]
Will close this for now, if we ever release a solid option I’ll re-open this one.

**Comment by usernamehw** [comment]
It looks like now it should be possible for extension to contribute those icons: https://github.com/microsoft/vscode/issues/92791.

@misolori Could you please share the `.svg` icon files from the solid icon set (if you still have them)? I do not mean to distribute them (for personal use).

**Comment by miguelsolorio** [comment]
@usernamehw I don't have those anymore but I'm sure you can download an old version of the repo from June/July 2019 and searching for the svgs in there. You can also search through the [previous PRs](https://github.com/microsoft/vscode/pull/74818) and seeing if you can grab those from there.

**Comment by usernamehw** [comment]
Thanks. Found it https://github.com/microsoft/vscode/pull/73914
