### ISSUE TITLE
No icons for back and forward

### ISSUE THREAD

**Issue by phatmann** [microsoft/vscode-icons#10]
The Touch Bar has icons for back and forward but those icons are not in this repository. They are needed by any extension that wants to add back or forward buttons to the tool bar.

**Comment by miguelsolorio** [comment]
> They are needed by any extension that wants to add back or forward buttons to the tool bar

I don't understand why an extension would need to provide icons for what already exists on the toolbar. Can you please elaborate?

And these are just using the same chevrons as `chevron-left` and `chevron-right`.

**Comment by phatmann** [comment]
Ah, the chevrons are the ones! I will close this issue.

But a question: I cannot find a way to add back and forward buttons to the VS toolbar without an extension. Is there a way to do it?

I am using the Back and Forth extension for this purpose. I asked the developer to change the icons to the chevrons, as they are currently using the arrows.

Thanks for your time.

**Comment by miguelsolorio** [comment]
@phatmann we don't offer this natively so it would need to be added via an extension, besides using the command palette as well.
