### ISSUE TITLE
Terminal icon is missing

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode-icons#13]
Terminal icon from https://code.visualstudio.com/api/references/icons-in-labels is missing in this repo.

**Comment by miguelsolorio** [comment]
This is actually the same icon as `console`, it's only listed twice as `terminal` on our website as a reference from previous [Octicon](https://octicons.github.com/icon/terminal/) references:


| Name | Icon | Links |
|---|---|--|
console|<img width='16px' src='https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/console.svg?sanitize=true' />|[Light](https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/light/console.svg) / [Dark](https://raw.githubusercontent.com/microsoft/vscode-icons/master/icons/dark/console.svg)|

Let me know if this doesn't work for you.

**Comment by auchenberg** [comment]
Ah, thanks @misolori !
