### ISSUE TITLE
Icons don't work with WSL

### ISSUE THREAD

**Issue by JetUni** [microsoft/vscode-icons#14]
When working on WSL, the icons don't apply to the files. I looked at the extensions and it said this extension was installed locally, but not on my WSL instance (Ubuntu-18.04). How can it be installed in WSL?

**Comment by miguelsolorio** [comment]
@JetUni I don't think I follow, what are you trying to do with the icons and WSL?

**Comment by JetUni** [comment]
I have VS code connected to WSL and I have this extension installed, but none of the icons are showing up like they should

**Comment by miguelsolorio** [comment]
@JetUni which extension? This repo is not for any extension.

**Comment by JetUni** [comment]
Sorry, I must have this confused with another repo with the same name!
