### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by panekj** [microsoft/vscode-icons#18]
Hi, could you please describe relation/difference between this repository and https://github.com/microsoft/vscode-codicons?
It seems that icons have been migrated to mentioned repo and whole set is developed there.
If it's true, could it be mentioned in readme and/or could the repository be archived?

**Comment by miguelsolorio** [comment]
[vscode-codicons](https://github.com/microsoft/vscode-codicons) is the icon font repository that is used in VS Code. This repository is solely for the icons themselves, we try to periodically update this repository with the latest icons. Does this answer your question?

**Comment by panekj** [comment]
Sure
