### ISSUE TITLE
the "cancel search" could be improved. It looks like a person icon

### ISSUE THREAD

**Issue by gianpaj** [microsoft/vscode-icons#4]
In my opinion, the new icon for "cancel search" looks like a person icon.

A suggestion would be a "stop sign". Maybe something like this?

![EDuP9n2WkAADMPg](https://user-images.githubusercontent.com/899175/64372184-f474a600-d02a-11e9-95ab-b9ea6c2546ae.jpeg)

PS: thanks for working VSCode and keep improving the UX for millions of developers out there! ✨

**Comment by misolori** [comment]
Thanks for the suggestion, we did iterate on this quite a bit and went through several options (including the stop one like you suggested). In the end the team felt this one represented it best.

Also, in the future if you have any issues/suggestions, please post in the main [vscode repo](https://github.com/microsoft/vscode).
