### ISSUE TITLE
The icon is too ugly. How to change back the previous Icon

### ISSUE THREAD

**Issue by Gxuebin** [microsoft/vscode-icons#6]
The icon is too ugly.
![image](https://user-images.githubusercontent.com/20697809/65206821-64bb0700-dac2-11e9-9609-f8b2f4894d90.png)

How can I change back the previous icon?
![image](https://user-images.githubusercontent.com/20697809/65206837-6edd0580-dac2-11e9-99f2-699d628e4e08.png)

**Comment by miguelsolorio** [comment]
This repo is for the icons assets, anything else related to the product and direction please file an issue with the main [microsoft/vscode](https://github.com/microsoft/vscode) repo. The only to go back to the previous version is to downgrade to a previous version.
